---
apiVersion: v1
kind: ConfigMap
metadata:
  name: candy-service-config
  labels:
    app: candy-service
data:
  candy.cfg: |-
    candy.peppermint.power=100000000
    candy.nougat-armor.strength=10
    candy.lemon.acceptability=0
...

---
apiVersion: v1
kind: Secret
metadata:
  name:  db-password
stringData:
   password:  Kub3rn3t3sRul3s!
...
 
---
apiVersion: v1
kind: Pod
metadata:
  name: candy-service-pod
  labels:
    name: candy-service
spec:
  securityContext:
    fsGroup: 2000
  serviceAccountName: candy-svc
  containers:
  - name: candy-service-container
    image: linuxacademycontent/candy-service:1
    volumeMounts:
      - name: config-volume
        mountPath: /etc/candy-service
    env:
      - name: DB_PASSWORD
        valueFrom:
           secretKeyRef:
              name: db-password
              key: password
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumes:
      - name: config-volume
        configMap:
            name: candy-service-config
...



