---
apiVersion: v1
kind: Namespace
metadata: 
  name: mynamespace
...

---
apiVersion: v1
kind: Pod
metadata:
  name: my-simple-nginx-pod
  namespace: mynamespace
spec:
  containers:
    - name: my-simple-nginx-container
      image: nginx