---
apiVersion: v1
kind: Namespace
metadata:
  name:  web
...  
---
apiVersion: v1
kind: Pod
metadata: 
  name: my-simple-nginx-pod
  namespace: web
spec:
  containers:
    - name: my-simple-nginx-container
      image: nginx
      command: ["nginx"]
      args: ["-g", "daemon off;", "-q"]
      ports:
        - containerPort: 80
...
